const actionTypes = {
    LOGIN: 'LOGIN',
    REGISTER_SUCCESS: 'REGISTER_SUCCESS',
    REGISTER_FAIL: 'REGISTER_FAIL',
    LOGOUT: 'LOGOUT',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAIL: 'LOGIN_FAIL',
    GET_POSTS: 'GET_POSTS',
    GET_POSTS_LIMIT: 'GET_POSTS_LIMIT',
    GET_POST_ADMIN: 'GET_POST_ADMIN',
    GET_NEW_POST: 'GET_NEW_POST',
    GET_NEWS_OUTSTANDING: 'GET_NEWS_OUTSTANDING',
    EDIT_DATA: 'EDIT_DATA',
    RESET_EDIT_DATA: 'RESET_EDIT_DATA',



    GET_CATAGORIES: "GET_CATAGORIES",
    GET_PRICES: "GET_PRICES",
    GET_AREAS: "GET_AREAS",
    GET_PROVINCES: "GET_PROVINCES",

    // User
    GET_USER_CURRENT: "GET_USER_CURRENT",


}

export default actionTypes